name: "embeddings-api"
services:
  server:
    container_name: server
    platform: linux/x86_64
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    command: bun dev
    ports:
      - 8080:8080
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/node_modules
    restart: always
